user:
  count: 940
  test: 950
server:
  port: 8100
spring:
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: order_keyspace
      local-datacenter: datacenter1
      schema-action: create_if_not_exists
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1