user:
  count: 940
  test: 950
server:
  port: 8100
spring:
  config:
    import: optional:configserver:http://localhost:8500
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: secret
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1