user:
  count: 940
  test: 950
server:
  port: 8200
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb

#eureka:  
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1