user:
  count: 840
  test: 883747
server:
  port: 8300
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: secret
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1